## DOF accessor
int32 X=0
int32 Y=1
int32 Z=2
int32 K=3
int32 M=4
int32 N=5

## Manual generators
int32 DISABLED=0
int32 EFFORT=1
int32 SPEED=2
int32 POSITION=3

## Select manual
int32[6] use_generator
---
