# Controller parent name - for multi-controller nodes
string parent
# Controller unique name
string name
# If the controller has a manual mode
bool hasManual
# Used tau
int8[6] used_tau
# Used other controllers by name
string[] used_other
# Used resources and required controllers
string[] used_resources
---
uint8 SUCCESS = 0
uint8 MISSING_DEPENDENCY = 1
uint8 ALREADY_REGISTERED = 2

uint8 reply